package org.jclarity.training.chapter11;

import javax.persistence.*;

@Entity 
public class User {
    @Id // @Id indicates that this it a unique primary key
    @GeneratedValue // @GeneratedValue indicates that value is automatically generated by the server
    private Long id;

    private String name;

    // note that no setter for ID is provided, Hibernate will generate the ID for us
    public long getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}